# Generated by Django 4.1.2 on 2022-10-15 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baner_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('title1', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Counters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_for_sale', models.IntegerField(default='0')),
                ('counter_for_rent', models.IntegerField(default='0')),
                ('brokers', models.IntegerField(default='0')),
                ('agents', models.IntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Recently_Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='Recently_Properties/')),
                ('for_rent', models.CharField(blank=True, max_length=250, null=True)),
                ('for_sale', models.CharField(blank=True, max_length=250, null=True)),
                ('price', models.FloatField(blank=True, default='0.00', null=True)),
                ('title', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('sqr_feet', models.CharField(max_length=250)),
                ('bedrooms', models.CharField(max_length=250)),
                ('bathrooms', models.CharField(max_length=250)),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='indexApp.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Features_property_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_pic', models.ImageField(null=True, upload_to='features_post_img/')),
                ('price', models.FloatField(default='0.00')),
                ('post_title', models.CharField(max_length=250, null=True)),
                ('sqr_feet', models.CharField(max_length=250)),
                ('bedrooms', models.CharField(max_length=250)),
                ('bathrooms', models.CharField(max_length=250)),
                ('garage', models.CharField(max_length=250)),
                ('developer_name', models.CharField(blank=True, max_length=250, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('post_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='indexApp.location')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
