# Generated by Django 4.1.2 on 2022-10-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0003_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='email',
            field=models.EmailField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='address',
            field=models.CharField(max_length=250),
        ),
    ]
