# Generated by Django 4.1.2 on 2022-10-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0004_agent_email_alter_agent_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='fax',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='agent',
            name='mobile',
            field=models.CharField(max_length=250),
        ),
    ]
