# Generated by Django 4.1.2 on 2022-10-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0006_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='office_img',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='client_img',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='project_img',
        ),
        migrations.AddField(
            model_name='gallery',
            name='img_type',
            field=models.CharField(blank=True, choices=[('Office', 'Office'), ('Client', 'Client')], max_length=100, null=True),
        ),
    ]
