# Generated by Django 4.1.2 on 2022-10-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0007_rename_office_img_gallery_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/office'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='img_type',
            field=models.CharField(blank=True, choices=[('Office', 'Office'), ('Client', 'Client'), ('Project', 'Project')], max_length=100, null=True),
        ),
    ]
