# Generated by Django 4.1.2 on 2022-10-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0008_alter_gallery_img_alter_gallery_img_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/office/'),
        ),
    ]
