# Generated by Django 4.1.2 on 2022-10-19 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0009_alter_gallery_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_pic', models.ImageField(null=True, upload_to='features_post_img/')),
                ('price', models.FloatField(default='0.00')),
                ('post_title', models.CharField(max_length=250, null=True)),
                ('post_type', models.CharField(choices=[('feature', 'feature'), ('apartment', 'apartment'), ('land', 'land'), ('recent', 'recent')], max_length=100)),
                ('sqr_feet', models.CharField(max_length=250)),
                ('bedrooms', models.CharField(max_length=250)),
                ('bathrooms', models.CharField(max_length=250)),
                ('garage', models.CharField(max_length=250)),
                ('developer_name', models.CharField(blank=True, max_length=250, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('post_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='indexApp.location')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.DeleteModel(
            name='Features_property_post',
        ),
    ]
