# Generated by Django 4.1.2 on 2022-10-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0014_career_contactus_notice_ourteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=150)),
                ('expected_salary', models.CharField(max_length=150)),
                ('cv', models.FileField(upload_to='ApplicationCV')),
                ('message', models.TextField()),
            ],
        ),
    ]
