# Generated by Django 4.1.2 on 2022-10-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0016_post_related_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_location',
        ),
        migrations.AddField(
            model_name='post',
            name='post_location',
            field=models.ManyToManyField(blank=True, null=True, related_name='location', to='indexApp.location'),
        ),
    ]
