# Generated by Django 4.1.2 on 2022-10-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0018_remove_post_post_location_remove_post_post_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.ManyToManyField(related_name='pro_type', to='indexApp.property_type'),
        ),
    ]
