# Generated by Django 4.1.2 on 2022-10-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0023_remove_post_garage_remove_post_sqr_feet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='apartment_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='land_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='parking_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='total_apartment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
