# Generated by Django 4.1.2 on 2022-10-27 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0024_alter_post_apartment_size_alter_post_bathrooms_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='parking_position',
            new_name='parking_area',
        ),
    ]
