# Generated by Django 4.1.2 on 2022-10-29 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0027_feedback_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Property_Post',
        ),
        migrations.AddField(
            model_name='feedback',
            name='property_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fb_pro_name', to='indexApp.property_post'),
        ),
    ]
