# Generated by Django 4.1.2 on 2022-10-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0029_rename_property_name_feedback_property_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='property_id',
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_feedback_show',
            field=models.BooleanField(null=True),
        ),
    ]
