# Generated by Django 4.1.2 on 2022-10-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0030_remove_feedback_property_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='is_feedback_show',
            field=models.BooleanField(default=True),
        ),
    ]
