# Generated by Django 4.1.2 on 2022-10-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0032_alter_feedback_is_feedback_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_post',
            name='floor_plan_image',
            field=models.ImageField(null=True, upload_to='floor_plan_image/'),
        ),
    ]
