# Generated by Django 4.1.2 on 2022-10-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0035_alter_property_post_post_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_post',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
