# Generated by Django 4.1.2 on 2022-10-29 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0036_alter_property_post_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property_post',
            old_name='floor_plan_image',
            new_name='floor_plan_image_or_land_layout_img',
        ),
    ]
