# Generated by Django 4.1.2 on 2022-10-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0037_rename_floor_plan_image_property_post_floor_plan_image_or_land_layout_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Why_chosse_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Why_chosse_us',
                'verbose_name_plural': 'Why_chosse_us',
            },
        ),
    ]
