# Generated by Django 4.1.2 on 2022-10-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0038_why_chosse_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='Why_chosse_us_option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Why_chosse_us_option',
                'verbose_name_plural': 'Why_chosse_us_options',
            },
        ),
        migrations.RemoveField(
            model_name='why_chosse_us',
            name='title',
        ),
        migrations.AddField(
            model_name='why_chosse_us',
            name='title',
            field=models.ManyToManyField(related_name='why_choose', to='indexApp.why_chosse_us_option'),
        ),
    ]
