# Generated by Django 4.1.2 on 2022-10-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0039_why_chosse_us_option_remove_why_chosse_us_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name': 'Why_chosse_us_option', 'verbose_name_plural': 'Why_chosse_us_options'},
        ),
        migrations.RemoveField(
            model_name='why_chosse_us',
            name='title',
        ),
        migrations.DeleteModel(
            name='Why_chosse_us_option',
        ),
        migrations.AddField(
            model_name='why_chosse_us',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
