# Generated by Django 4.1.2 on 2022-10-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0041_rename_property_post_propertypost'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to='about-us_img/')),
                ('shadow_image', models.ImageField(upload_to='about-us_img/')),
                ('experience_year', models.IntegerField()),
            ],
        ),
    ]
