# Generated by Django 4.1.2 on 2022-10-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0042_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
