# Generated by Django 4.1.2 on 2022-10-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0044_aboutlookingsection_alter_aboutus_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutTestimotial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('short_description', models.TextField()),
                ('image', models.ImageField(upload_to='about-us_img/')),
            ],
            options={
                'verbose_name': 'AboutTestimotial',
                'verbose_name_plural': 'About Testimotial',
            },
        ),
    ]
