# Generated by Django 4.1.2 on 2022-10-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0045_abouttestimotial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='property_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
