# Generated by Django 4.1.2 on 2022-10-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0046_feedback_property_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTypeFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'PropertyType',
                'verbose_name_plural': 'Project Type Filter',
            },
        ),
        migrations.CreateModel(
            name='PropertyTypeFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'PropertyType',
                'verbose_name_plural': 'Property Type Filter',
            },
        ),
        migrations.AlterField(
            model_name='gallery',
            name='img_type',
            field=models.CharField(blank=True, choices=[('Management', 'Management'), ('Realstate Property', 'Realstate Property'), ('E-commerce', 'E-commerce'), ('Client Area', 'Client Area')], max_length=100, null=True),
        ),
    ]
