# Generated by Django 4.1.2 on 2022-10-30 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0047_projecttypefilter_propertytypefilter_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectTypeFilter',
        ),
        migrations.DeleteModel(
            name='PropertyTypeFilter',
        ),
    ]
