# Generated by Django 4.1.2 on 2022-10-30 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0048_delete_projecttypefilter_delete_propertytypefilter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTypeFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'ProjectTypeFilter',
                'verbose_name_plural': 'Project Type Filter',
            },
        ),
        migrations.CreateModel(
            name='PropertyTypeFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'ProjectTypeFilter',
                'verbose_name_plural': 'Property Type Filter',
            },
        ),
        migrations.AddField(
            model_name='propertypost',
            name='project_type_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indexApp.projecttypefilter'),
        ),
    ]
