# Generated by Django 4.1.2 on 2022-10-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0049_projecttypefilter_propertytypefilter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='services/')),
                ('service_type', models.ManyToManyField(related_name='service', to='indexApp.servicetype')),
            ],
        ),
    ]
