# Generated by Django 4.1.2 on 2022-11-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0051_servicepost_created_servicetype_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queations', models.CharField(max_length=250)),
                ('answers', models.TextField()),
            ],
        ),
    ]
