# Generated by Django 4.1.2 on 2022-11-03 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0053_bookingnow'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'BookingPropertyType',
                'verbose_name_plural': 'Booking Property Type',
            },
        ),
        migrations.AlterField(
            model_name='bookingnow',
            name='property_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indexApp.bookingpropertytype'),
        ),
    ]
