# Generated by Django 4.1.2 on 2022-11-06 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0054_bookingpropertytype_alter_bookingnow_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertypost',
            name='broucher',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='propertypost',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='propertypost',
            name='video_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='propertytypefilter',
            name='project_type_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_type_filters', to='indexApp.projecttypefilter'),
        ),
    ]
