# Generated by Django 4.1.2 on 2022-11-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0055_propertypost_broucher_propertypost_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertypost',
            name='broucher',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='file/'),
        ),
    ]
