# Generated by Django 4.1.2 on 2022-11-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0057_propertypost_video_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertypost',
            name='video_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
