# Generated by Django 4.1.2 on 2022-11-06 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0058_alter_propertypost_video_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertypost',
            name='video_title',
        ),
    ]
