# Generated by Django 4.1.2 on 2022-11-07 04:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0060_bookingnow_property_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingnow',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^(\\+?\\d{0,4})?\\s?-?\\s?(\\(?\\d{3}\\)?)\\s?-?\\s?(\\(?\\d{3}\\)?)\\s?-?\\s?(\\(?\\d{4}\\)?)?$', 'The phone number provided is invalid')]),
        ),
    ]
