# Generated by Django 4.1.2 on 2022-11-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0061_alter_bookingnow_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='is_feedback_show',
            field=models.BooleanField(default=True),
        ),
    ]
