# Generated by Django 4.1.2 on 2022-11-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0063_alter_feedback_is_feedback_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertytypefilter',
            name='project_type_filter',
        ),
        migrations.AddField(
            model_name='propertytypefilter',
            name='project_type_filter',
            field=models.ManyToManyField(blank=True, null=True, related_name='project_type_filters', to='indexApp.projecttypefilter'),
        ),
    ]
