# Generated by Django 4.1.2 on 2022-11-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0065_rename_project_type_filter_propertytypefilter_property_type_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertytypefilter',
            name='property_type_filter',
        ),
        migrations.AddField(
            model_name='projecttypefilter',
            name='property_type_filter',
            field=models.ManyToManyField(blank=True, related_name='property_type_filtered', to='indexApp.propertytypefilter'),
        ),
    ]
