# Generated by Django 4.1.2 on 2022-11-07 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0066_remove_propertytypefilter_property_type_filter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttypefilter',
            name='property_type_filter',
        ),
        migrations.AddField(
            model_name='propertypost',
            name='property_type_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indexApp.propertytypefilter'),
        ),
    ]
