# Generated by Django 4.1.2 on 2022-11-09 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0067_remove_projecttypefilter_property_type_filter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertypost',
            old_name='project_type_filter',
            new_name='select_project_type',
        ),
        migrations.RenameField(
            model_name='propertypost',
            old_name='property_type_filter',
            new_name='select_property_type',
        ),
        migrations.AddField(
            model_name='propertypost',
            name='select_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indexApp.division'),
        ),
    ]
