# Generated by Django 4.1.2 on 2022-11-09 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0068_rename_project_type_filter_propertypost_select_project_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertypost',
            name='select_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indexApp.district'),
        ),
    ]
