# Generated by Django 4.1.2 on 2022-11-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0069_propertypost_select_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertypost',
            name='price',
            field=models.FloatField(blank=True, default='0.00', null=True),
        ),
    ]
