# Generated by Django 4.1.2 on 2022-11-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0070_alter_propertypost_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='career',
            options={'ordering': ['-post_date']},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='servicepost',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='career',
            name='job_description',
            field=models.CharField(max_length=500),
        ),
    ]
