# Generated by Django 4.1.2 on 2022-11-14 05:57

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0071_alter_career_options_alter_gallery_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='job_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
