# Generated by Django 4.1.2 on 2022-11-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0072_alter_career_job_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='career',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['-id'], 'verbose_name': 'ContactUs', 'verbose_name_plural': 'ContactUs'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='contactus',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('read', 'read')], max_length=100, null=True),
        ),
    ]
