# Generated by Django 4.1.2 on 2022-11-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0073_alter_career_options_alter_contactus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['-id'], 'verbose_name': 'ContactUs', 'verbose_name_plural': 'Contact Us'},
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('read', 'read')], max_length=100, null=True),
        ),
    ]
