# Generated by Django 4.1.2 on 2022-11-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0074_alter_contactus_options_jobapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('read', 'read')], max_length=100, null=True),
        ),
    ]
