# Generated by Django 4.1.5 on 2023-01-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0077_alter_propertypost_post_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_social_link', models.CharField(blank=True, max_length=500, null=True)),
                ('twitter_social_link', models.CharField(blank=True, max_length=500, null=True)),
                ('instagram_social_link', models.CharField(blank=True, max_length=500, null=True)),
                ('youtube_social_link', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='bookingpropertytype',
            options={'verbose_name_plural': 'Booking Property Types'},
        ),
    ]
