# Generated by Django 4.1.5 on 2023-01-08 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0078_socialmedialink_alter_bookingpropertytype_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmedialink',
            old_name='instagram_social_link',
            new_name='linkedin_social_link',
        ),
    ]
