# Generated by Django 4.1.5 on 2023-01-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0079_rename_instagram_social_link_socialmedialink_linkedin_social_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedialink',
            name='instagram_social_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
