# Generated by Django 4.1.5 on 2023-02-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0080_socialmedialink_instagram_social_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='CSR/')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
