# Generated by Django 4.1.5 on 2023-02-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0081_csr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csr',
            options={'verbose_name_plural': 'CSR'},
        ),
        migrations.AlterField(
            model_name='csr',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
