# Generated by Django 4.1.6 on 2023-02-15 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0082_alter_csr_options_alter_csr_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baner_video',
            old_name='video_link',
            new_name='image',
        ),
    ]
