# Generated by Django 4.1.6 on 2023-02-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0083_rename_video_link_baner_video_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baner_video',
            name='title',
        ),
        migrations.RemoveField(
            model_name='baner_video',
            name='title1',
        ),
        migrations.AlterField(
            model_name='baner_video',
            name='image',
            field=models.ImageField(upload_to='banner_images/'),
        ),
    ]
