# Generated by Django 4.2.11 on 2025-01-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0084_remove_baner_video_title_remove_baner_video_title1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baner_video',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='baner_video',
            name='url_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
