# Generated by Django 4.2.11 on 2025-01-06 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0085_baner_video_title_baner_video_url_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baner_video',
            name='url_link',
        ),
    ]
