# Generated by Django 5.1.4 on 2025-01-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0086_remove_baner_video_url_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingnow',
            name='read_status',
            field=models.BooleanField(default=False),
        ),
    ]
