# Generated by Django 5.1.4 on 2025-01-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0087_bookingnow_read_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouttestimotial',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='abouttestimotial',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
