# Generated by Django 5.1.4 on 2025-01-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0088_abouttestimotial_title_abouttestimotial_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertypost',
            name='apartment_size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
