# Generated by Django 5.1.3 on 2025-02-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0090_awards_corparate_structure_md_message_missionvision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='awards',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='awards/image/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonial/image/'),
        ),
    ]
