# Generated by Django 5.1.3 on 2025-02-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0091_awards_image_testimonial_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='md_message',
            options={'verbose_name_plural': 'MD Message'},
        ),
        migrations.RemoveField(
            model_name='corparate_structure',
            name='details',
        ),
        migrations.AddField(
            model_name='corparate_structure',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='corparate_structure/image/'),
        ),
    ]
