# Generated by Django 5.1.3 on 2025-02-06 06:37

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0092_alter_md_message_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Land_Wanted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tilte', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='land-wanted/image/')),
                ('details', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
