# Generated by Django 5.1.3 on 2025-02-23 07:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0097_alter_aboutus_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
