# Generated by Django 5.1.3 on 2025-02-25 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0098_alter_blog_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awards',
            old_name='tilte',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='corparate_structure',
            old_name='tilte',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='land_wanted',
            old_name='tilte',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='md_message',
            old_name='tilte',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='missionvision',
            old_name='tilte',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='our_certificate',
            old_name='tilte',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='social_responsibility',
            old_name='tilte',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='tilte',
            new_name='title',
        ),
    ]
