# Generated by Django 5.1.3 on 2025-02-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0099_rename_tilte_awards_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='md_message',
            name='image',
            field=models.ImageField(null=True, upload_to='md_message/images/'),
        ),
    ]
