# Generated by Django 5.1.3 on 2025-02-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0100_md_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='social_responsibility',
            name='banner',
            field=models.ImageField(null=True, upload_to='social_responsibility/images/'),
        ),
    ]
