# Generated by Django 5.1.3 on 2025-02-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0101_social_responsibility_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertypost',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
