# Generated by Django 5.1.3 on 2025-02-26 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0102_propertypost_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertypost',
            old_name='feedback',
            new_name='feature',
        ),
    ]
