# Generated by Django 5.1.3 on 2025-03-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0103_rename_feedback_propertypost_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='why_chosse_us',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
