# Generated by Django 5.1.3 on 2025-03-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0104_why_chosse_us_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='why_chosse_us',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='whychoose/image/'),
        ),
    ]
