# Generated by Django 5.1.3 on 2025-03-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0105_alter_why_chosse_us_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='email',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
