# Generated by Django 5.1.3 on 2025-03-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0106_remove_newsletter_email_newsletter_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_Galary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video_url', models.URLField(max_length=250)),
                ('published_by', models.CharField(max_length=100)),
            ],
        ),
    ]
