# Generated by Django 4.2 on 2025-06-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0107_video_galary'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertypost',
            name='map_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
