# Generated by Django 4.2 on 2025-06-29 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0108_propertypost_map_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SisterConcern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='sister_concerns/sister-concerns-image/')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexApp.country')),
            ],
        ),
    ]
