# Generated by Django 4.2 on 2025-06-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0109_country_sisterconcern'),
    ]

    operations = [
        migrations.AddField(
            model_name='sisterconcern',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sisterconcern',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sisterconcern',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text='Google Maps embed URL', null=True),
        ),
        migrations.AddField(
            model_name='sisterconcern',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sisterconcern',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
