# Generated by Django 4.2 on 2025-06-30 10:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0110_sisterconcern_address_sisterconcern_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_location', models.CharField(max_length=200)),
                ('applicant_type', models.CharField(choices=[('individual', 'Individual'), ('joint', 'Joint'), ('corporate', 'Corporate')], max_length=20)),
                ('full_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('same_as_present_address', models.BooleanField(default=False)),
                ('nationality', models.CharField(default='Bangladeshi', max_length=50)),
                ('religion', models.CharField(choices=[('islam', 'Islam'), ('hinduism', 'Hinduism'), ('christianity', 'Christianity'), ('buddhism', 'Buddhism'), ('other', 'Other')], max_length=20)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('nid_passport', models.CharField(max_length=50)),
                ('tin', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.DateField()),
                ('applicant_photo', models.ImageField(blank=True, null=True, upload_to='booking/applicants/')),
                ('unit_type', models.CharField(max_length=20)),
                ('project_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_unit', models.CharField(max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_number', models.CharField(max_length=20)),
                ('floor_number', models.CharField(max_length=20)),
                ('booking_money', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('pay_order', 'Pay Order'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('nid_copy', models.FileField(blank=True, null=True, upload_to='booking/documents/nid/')),
                ('photo_copy', models.ImageField(blank=True, null=True, upload_to='booking/documents/photos/')),
                ('tin_copy', models.FileField(blank=True, null=True, upload_to='booking/documents/tin/')),
                ('other_documents', models.FileField(blank=True, null=True, upload_to='booking/documents/others/')),
                ('terms_agreed', models.BooleanField(default=False)),
                ('signature_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference_no', models.CharField(blank=True, max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sisterconcern',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text='Google Maps embed URL', max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='PaymentInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='indexApp.propertybooking')),
            ],
            options={
                'ordering': ['installment_number'],
            },
        ),
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('relation', models.CharField(choices=[('spouse', 'Spouse'), ('child', 'Child'), ('parent', 'Parent'), ('sibling', 'Sibling'), ('other', 'Other')], max_length=20)),
                ('nid_passport', models.CharField(max_length=50)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='booking/nominees/')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominees', to='indexApp.propertybooking')),
            ],
        ),
    ]
