# Generated by Django 4.2 on 2025-07-02 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0111_propertybooking_alter_sisterconcern_map_embed_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinstallment',
            name='booking',
        ),
        migrations.DeleteModel(
            name='Nominee',
        ),
        migrations.DeleteModel(
            name='PaymentInstallment',
        ),
        migrations.DeleteModel(
            name='PropertyBooking',
        ),
    ]
