# Generated by Django 4.2 on 2025-07-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0112_remove_paymentinstallment_booking_delete_nominee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_full_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(blank=True, max_length=255)),
                ('spouse_name', models.CharField(blank=True, max_length=255)),
                ('mailing_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('nid_or_passport', models.CharField(max_length=100)),
                ('tin', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=100)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], max_length=20)),
                ('marriage_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('profession', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('nominee_name', models.CharField(max_length=255)),
                ('nominee_relation', models.CharField(max_length=100)),
                ('nominee_nid', models.CharField(max_length=100)),
                ('nominee_mobile', models.CharField(max_length=20)),
                ('residence_type', models.CharField(choices=[('Resident', 'Resident'), ('Non Resident', 'Non Resident')], max_length=20)),
                ('project_location', models.TextField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('per_share_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_project_area', models.CharField(max_length=100)),
                ('number_of_share', models.PositiveIntegerField()),
                ('instruction', models.TextField(blank=True)),
                ('booking_money', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_type', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('PO', 'PO'), ('DD', 'DD')], max_length=20)),
                ('reference_no', models.CharField(max_length=100)),
                ('payment_date', models.DateField()),
                ('bank', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('down_payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('down_payment_due_date', models.DateField()),
                ('rest_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('num_installments', models.PositiveIntegerField()),
                ('per_installment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('installment_start', models.DateField()),
                ('mode_of_payment', models.CharField(choices=[('At-A-Time', 'At-A-Time'), ('Installment', 'Installment')], max_length=20)),
                ('amount_in_words', models.CharField(max_length=500)),
                ('candidate_photo', models.ImageField(upload_to='realestate/photos/')),
                ('nominee_photo', models.ImageField(upload_to='realestate/photos/')),
                ('share_area', models.CharField(max_length=100)),
                ('agree_terms', models.BooleanField(default=False)),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
