# Generated by Django 4.2 on 2025-07-02 04:36

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0113_realestateapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealstateTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
