# Generated by Django 4.2 on 2025-07-02 05:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0114_realstateterms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestateapplication',
            name='amount_in_words',
        ),
        migrations.RemoveField(
            model_name='realestateapplication',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='realestateapplication',
            name='booking_money',
        ),
        migrations.RemoveField(
            model_name='realestateapplication',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='realestateapplication',
            name='down_payment',
        ),
        migrations.RemoveField(
            model_name='realestateapplication',
            name='down_payment_due_date',
        ),
        migrations.RemoveField(
            model_name='realestateapplication',
            name='installment_start',
        ),
        migrations.RemoveField(
            model_name='realestateapplication',
            name='mailing_address',
        ),
        migrations.RemoveField(
            model_name='realestateapplication',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='realestateapplication',
            name='mode_of_payment',
        ),
        migrations.RemoveField(
            model_name='realestateapplication',
            name='num_installments',
        ),
        migrations.RemoveField(
            model_name='realestateapplication',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='realestateapplication',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='realestateapplication',
            name='per_installment',
        ),
        migrations.RemoveField(
            model_name='realestateapplication',
            name='reference_no',
        ),
        migrations.RemoveField(
            model_name='realestateapplication',
            name='rest_amount',
        ),
        migrations.RemoveField(
            model_name='realestateapplication',
            name='spouse_name',
        ),
        migrations.AlterField(
            model_name='realestateapplication',
            name='residence_type',
            field=models.CharField(choices=[('Resident', 'Resident'), ('Non Resident', 'Non Resident'), ('Apartment', 'Apartment'), ('Floor', 'Floor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='realstateterms',
            name='terms',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
