# Generated by Django 4.2 on 2025-07-02 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0115_remove_realestateapplication_amount_in_words_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestateapplication',
            name='candidate_photo',
        ),
        migrations.RemoveField(
            model_name='realestateapplication',
            name='nid_or_passport',
        ),
        migrations.RemoveField(
            model_name='realestateapplication',
            name='nominee_mobile',
        ),
        migrations.RemoveField(
            model_name='realestateapplication',
            name='nominee_name',
        ),
        migrations.RemoveField(
            model_name='realestateapplication',
            name='nominee_nid',
        ),
        migrations.RemoveField(
            model_name='realestateapplication',
            name='nominee_photo',
        ),
        migrations.RemoveField(
            model_name='realestateapplication',
            name='nominee_relation',
        ),
        migrations.RemoveField(
            model_name='realestateapplication',
            name='share_area',
        ),
        migrations.RemoveField(
            model_name='realestateapplication',
            name='tin',
        ),
    ]
