# Generated by Django 4.2 on 2025-07-02 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0116_remove_realestateapplication_candidate_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestateapplication',
            name='marriage_date',
        ),
    ]
