# Generated by Django 4.2 on 2025-07-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0117_remove_realestateapplication_marriage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateapplication',
            name='uploaded_pdf',
            field=models.FileField(blank=True, null=True, upload_to='realestate/uploads/'),
        ),
    ]
