# Generated by Django 4.2 on 2025-07-02 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0118_realestateapplication_uploaded_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestateapplication',
            name='uploaded_pdf',
        ),
        migrations.CreateModel(
            name='RealEstateUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_pdf', models.FileField(upload_to='realestate/uploads/')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='indexApp.realestateapplication')),
            ],
        ),
    ]
