# Generated by Django 4.2 on 2025-07-02 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0119_remove_realestateapplication_uploaded_pdf_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RealEstateUpload',
        ),
    ]
