# Generated by Django 4.2 on 2025-07-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0121_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='md_message',
            name='is_center',
            field=models.BooleanField(default=True),
        ),
    ]
