# Generated by Django 4.2 on 2025-07-19 10:17

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0122_md_message_is_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('details', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name_plural': 'Privacy',
            },
        ),
        migrations.AlterModelOptions(
            name='missionvision',
            options={'verbose_name_plural': 'Mission & Vision'},
        ),
    ]
