# Generated by Django 4.2 on 2025-07-22 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0123_privacy_alter_missionvision_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Baner_video',
            new_name='Banner',
        ),
    ]
