# Generated by Django 4.2 on 2025-07-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0124_rename_baner_video_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
