# Generated by Django 4.2 on 2025-07-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0125_banner_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='img_type',
        ),
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
