# Generated by Django 4.2 on 2025-07-23 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0126_remove_gallery_img_type_gallery_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='experience_year',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='shadow_image',
        ),
    ]
