# Generated by Django 4.2 on 2025-07-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0128_banner_description_banner_description_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='description_color',
            field=models.CharField(default='white', max_length=50),
        ),
        migrations.AlterField(
            model_name='banner',
            name='sub_title_color',
            field=models.CharField(default='white', max_length=50),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title_color',
            field=models.CharField(default='white', max_length=50),
        ),
    ]
