# Generated by Django 4.2 on 2025-07-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0129_alter_banner_description_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='why_chosse_us',
            name='bg_color',
            field=models.CharField(default='blue', max_length=100),
        ),
        migrations.AddField(
            model_name='why_chosse_us',
            name='description_color',
            field=models.CharField(default='white', max_length=100),
        ),
        migrations.AddField(
            model_name='why_chosse_us',
            name='title_color',
            field=models.CharField(default='white', max_length=100),
        ),
    ]
