# Generated by Django 4.2 on 2025-07-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0130_why_chosse_us_bg_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='why_chosse_us',
            name='bg_color',
            field=models.CharField(default='#2E67AF', max_length=100),
        ),
    ]
