# Generated by Django 4.2 on 2025-07-31 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0131_alter_why_chosse_us_bg_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='album/')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
            },
        ),
        migrations.AlterModelOptions(
            name='why_chosse_us',
            options={'verbose_name': 'Why Chosse US', 'verbose_name_plural': 'Why Chosse US'},
        ),
        migrations.AddField(
            model_name='gallery',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indexApp.album'),
        ),
    ]
