# Generated by Django 4.2 on 2025-07-31 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0133_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertypost',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
