# Generated by Django 4.2 on 2025-08-30 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0134_propertypost_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='link',
        ),
    ]
