# Generated by Django 4.2 on 2025-08-31 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0136_campingbanner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CampingBanner',
        ),
    ]
