# Generated by Django 4.2 on 2025-08-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0137_delete_campingbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampingBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camping_banner', models.ImageField(upload_to='camping_banner/')),
            ],
        ),
    ]
