# Generated by Django 4.2 on 2025-08-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0138_campingbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sisterconcern',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
