# Generated by Django 4.2 on 2025-09-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0140_alter_propertypost_apartment_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertypost',
            name='apartment_size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='propertypost',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertypost',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertypost',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertypost',
            name='developer_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='propertypost',
            name='facing',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertypost',
            name='feature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertypost',
            name='land_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertypost',
            name='lift',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertypost',
            name='map_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertypost',
            name='parking_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertypost',
            name='parking_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertypost',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='propertypost',
            name='total_apartment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertypost',
            name='video_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
