# Generated by Django 4.2 on 2025-09-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0141_alter_propertypost_apartment_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SisterConcernBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sister_concerns/banners/')),
            ],
        ),
    ]
