# Generated by Django 5.2.1 on 2025-09-08 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0142_sisterconcernbanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='description',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='description_color',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='sub_title_color',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='title_color',
        ),
    ]
