# Generated by Django 4.1.2 on 2022-11-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(blank=True, max_length=50, null=True)),
                ('admin_image', models.ImageField(blank=True, null=True, upload_to='admin_images/')),
                ('admin_logo', models.ImageField(blank=True, null=True, upload_to='admin_logos/')),
            ],
        ),
    ]
