# Generated by Django 4.1.2 on 2022-11-22 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='admin_logo',
            new_name='dashboard_logo',
        ),
    ]
