# Generated by Django 4.1.2 on 2022-11-23 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_admin_logo_admin_dashboard_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'ordering': ['-id']},
        ),
    ]
