# Generated by Django 5.1.4 on 2025-01-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_admin_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='dashboard_favicon',
            field=models.ImageField(blank=True, null=True, upload_to='admin_favicons/'),
        ),
    ]
