# Generated by Django 5.1.4 on 2025-01-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_admin_dashboard_favicon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='dashboard_favicon',
            new_name='favicon',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='dashboard_logo',
            new_name='logo',
        ),
        migrations.AddField(
            model_name='admin',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='phone2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
