# Generated by Django 5.1.4 on 2025-01-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_dashboard_favicon_admin_favicon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='email2',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
