# Generated by Django 5.1.3 on 2025-02-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_admin_email_admin_email2'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='address2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='phone3',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='phone4',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
