# Generated by Django 5.1.3 on 2025-02-23 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_admin_address2_admin_phone3_admin_phone4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='address2',
        ),
    ]
