# Generated by Django 4.2 on 2025-06-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_admin_address2'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='footer_logo',
            field=models.ImageField(blank=True, null=True, upload_to='footer_logos/'),
        ),
    ]
