# Generated by Django 4.2 on 2025-07-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_admin_footer_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='navbar_color',
            field=models.CharField(default='white', max_length=50),
        ),
    ]
