# Generated by Django 4.2 on 2025-07-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_admin_navbar_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='navbar_textcolor',
            field=models.CharField(default='black', max_length=50),
        ),
    ]
