# Generated by Django 4.2 on 2025-07-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_admin_navbar_textcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='navbar_color',
            field=models.CharField(default='transparent', max_length=50),
        ),
    ]
