# Generated by Django 4.2 on 2025-07-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_admin_navbar_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='navbar_textactivecolor',
            field=models.CharField(default='red', max_length=50),
        ),
        migrations.AddField(
            model_name='admin',
            name='navbar_texthovercolor',
            field=models.CharField(default='red', max_length=50),
        ),
    ]
